### ISSUE TITLE
Cannot be imported

### ISSUE THREAD

**Issue by egesu** [klodianimeri/angular2-horizontal-slider#1]
I'm using Angular 5.0.0.

Using `ng serve --aot`, I get this error:

`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /home/ege/public_html/mikodam-ui/node_modules/angular2-horizontal-slider/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /home/ege/public_html/mikodam-ui/node_modules/angular2-horizontal-slider/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in /home/ege/public_html/mikodam-ui/node_modules/angular2-horizontal-slider/node_modules/@angular/core/core.d.ts`

Using `ng serve`, I get this one:

```
WARNING in ./node_modules/angular2-horizontal-slider/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compiler.js:506:17)
    at /home/ege/public_html/mikodam-ui/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular2-horizontal-slider/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-horizontal-slider/angular2-horizontal-slider/angular2-horizontal-slider.es5.js
 @ ./src/app/category/category.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/angular2-horizontal-slider/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compiler.js:506:17)
    at /home/ege/public_html/mikodam-ui/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/ege/public_html/mikodam-ui/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular2-horizontal-slider/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular2-horizontal-slider/angular2-horizontal-slider/angular2-horizontal-slider.es5.js
 @ ./src/app/category/category.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by klodianimeri** [comment]
Hi egesu,

I rebuilt the component with the angular v5 dependencies.
Now it should work!
